#!/bin/bash

modes=(\
	"-i 	initialize (make comments.txt file for each student)"\
	"-g	parse comments for each student and save grades"\
	"-p 	make pdfs (convert markdown files to pdf)"\
	"-u	create upload directory (required format for uploading)"\
)

usage_message() {
	echo -e "\nUsage: grade <mode> <dir>\n"
	echo "modes:"
	for i in "${modes[@]}"; do
		echo "    $i"
	done
	echo ""
	exit
}

if [ "$#" != 2 ] ; then 
	usage_message
	exit 1
fi

mode=$1
dirname=$2
hwdir="$(realpath $2)"
updir=${hwdir}-upload
srcdir="${HOME}/bin/grading"

convert_md_to_pdf() {
	for dir in $hwdir/*/ ; do
		cd "${dir}/Feedback Attachment(s)"
		echo "Directory: ${dir}"
		mdpdf comments.md -t gr
		cd ../../
		echo ""
	done
}

make_upload_dir() {
	cp -r $hwdir $updir
	for dir in $updir/*/ ; do
		rm "${dir}/Feedback Attachment(s)/comments.txt"
		cd ../../
	done
	rm "${updir}/grades.csv"
	rm "${updir}/inprogress"
	mv "${updir}/grades2.csv" "${updir}/grades.csv"
	echo -e "Upload directory created: ${updir}"
	echo ""
}

while getopts "igpu" opt; do
	case ${opt} in
		i)
			echo -e "\nInitializing...\n"
			make -C "${HOME}/bin/grading" init
			;;
		g)
			echo -e "\nParsing comments...\n"
			make -C "${HOME}/bin/grading" save
			;;
		p)
			echo -e "\nConverting markdown files to pdf...\n"
			convert_md_to_pdf
			;;
		u)
			echo -e "\nMaking upload directory..."
			make_upload_dir
			;;
		\?)
			echo -e "\nYou twat."
			;;
	esac
done
