#!/bin/bash

linkdir="${HOME}/bin"

mkdir -p "${linkdir}/grading"
srcdir="${linkdir}/grading"

ln -sf "${PWD}/grade" "${linkdir}/"
ln -sf "${PWD}/grading.c" "${srcdir}/"
ln -sf "${PWD}/Makefile" ${srcdir}/ 
ln -sf "${PWD}/gradecomments.latex" ${srcdir}/ 
ln -sf "${PWD}/mdgrade" ${srcdir}/
