load: grading.c
	cc grading.c 
	./a.out ~/de/grading/examples/p2/

configure: grading.c
	cc grading.c -DCONFIGURE
	./a.out ~/de/grading/examples/p2/

save: grading.c
	cc grading.c -DSAVE 
	./a.out ~/de/grading/examples/p2/

